### ISSUE TITLE
Variable being passed as untyped out parameter is not noticed as being initialized

### ISSUE THREAD

**Issue by sglienke** [integrated-application-development/sonar-delphi#104]
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.0.0

### SonarQube version

10.3.0.82913 Community Edition

### Issue description

SonarDelphi raises `community-delphi:VariableInitialization` on the following code (Spring.ValueConverters.pas line 1540 - from 2.0.0 tag)

```
function TDateToStringConverter.DoConvertTo(const value: TValue;
  const targetTypeInfo: PTypeInfo; const parameter: TValue): TValue;
var
  format: TFormatSettings;
begin
  if not parameter.IsEmpty and parameter.TryAsType(TypeInfo(TFormatSettings), format) then
  begin
    case targetTypeInfo.Kind of
      tkString, tkUString:
        Result := TValue.From<string>(DateToStr(value.AsExtended, format)); // <-
```

The logic about this code is that via `parameter` a `TFormatSettings` will be passed and TryAsType has this signature:

`function TValueHelper.TryAsType(typeInfo: PTypeInfo; out target): Boolean;` - when it returns true then the out parameter is being filled. Since the type is being passed via the PTypeInfo parameter the out needs to be typeless.

### Steps to reproduce

Running SonarDelphi on Spring4D 2.0.0

**Comment by sglienke** [comment]
I think there is also another - albeit possibly a bit more difficult to detect one - in `Spring.pas` in `CompareValue`:

```
  else if IsNullable(left.TypeInfo) and IsNullable(right.TypeInfo) then
  begin
    leftIsEmpty := not left.TryGetNullableValue(leftValue);
    rightIsEmpty := not right.TryGetNullableValue(rightValue);
    if leftIsEmpty or rightIsEmpty then
      Result := EmptyResults[leftIsEmpty, rightIsEmpty]
    else
      Result := CompareValue(leftValue, rightValue);
  end else
```

The reasoning here is that `CompareValue` is only called when both `TryGetNullableValue` returned True and thus initialized `leftValue` and `rightValue` that were passed via the out parameter of that method.

**Comment by zaneduffield** [comment]
I think SonarDelphi is *supposed* to consider a variable initialised whenever it is passed as a var/out parameter (regardless of any specific return-value semantics). In this case that would mean the problem is a name-resolution failure on `TryAsType`, which could have something to do with it being from a helper class.

**Comment by Cirras** [comment]
Hi Stefan, thanks for the report.

As @zaneduffield noted, this is probably a name resolution failure on `TryAsType`.

We've reproduced the issue and will have a look.
