### ISSUE TITLE
Cardinal to Integer cast marked as redundant cast

### ISSUE THREAD

**Issue by sglienke** [integrated-application-development/sonar-delphi#105]
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.0.0

### SonarQube version

10.3.0.82913 Community Edition

### Issue description

Following code in Spring.HashTable.pas (line 732) is being marked with `community-delphi:RedundantCast`:

`        8: hashCode := Integer(PInt64Rec(@key).Cardinals[0] xor PInt64Rec(@key).Cardinals[1]) and not RemovedFlag;`

The cast of Cardinal to Integer is there for a reason: to suppress `W1071 Implicit integer cast with potential data loss from 'unsigned 32-bit integer' to 'Integer'`

### Steps to reproduce

Running SonarDelphi on Spring4D 2.0.0

**Comment by Cirras** [comment]
Hi Stefan, thanks for the report. 👍

Will follow up and figure out why this is currently being flagged.
