### ISSUE TITLE
Public methods that are not used are marked from UnusedRoutine rule

### ISSUE THREAD

**Issue by sglienke** [integrated-application-development/sonar-delphi#106]
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.0.0

### SonarQube version

10.3.0.82913 Community Edition

### Issue description

During the analysis of Spring4D it reported a bunch of public methods with the `UnusedRoutine` rule. While I understand that within a self contained project this would be valid but in library for others to use I consider these as false positive.

Since the very same rule probably also reports private methods that are not used which would be valid I don't just want to turn it off.

I don't know how the scanner works exactly but one solution could be that if the scanned units are part of a package public methods should not be reported.

### Steps to reproduce

Running SonarDelphi on Spring4D 2.0.0

**Comment by sglienke** [comment]
The same seems to be the case for the `UnusedProperty` rule.

**Comment by Cirras** [comment]
Hi @sglienke,

Thanks for reporting this. I wouldn't classify it as a **bug**, but agree that it's a significant usability issue for libraries.

Perhaps the `Unused*` rules could get an `excludePublic` property to exclude public visibility in addition to published (which is already excluded).

Would that satisfy your use-case?

**Comment by Cirras** [comment]
Hi @sglienke,

For this one I'm currently thinking:
* new property on (most) `Unused*` rules called `excludePublicInterface`
* if enabled, `excludePublicInterface` will exclude any declaration with public visibility **within the interface section of a unit**.

I feel like this should cater to the library use case pretty well, do you see any obvious problems here?

**Comment by Cirras** [comment]
Alternatively, I might name it `excludeApi`.

**Comment by sglienke** [comment]
Could this be inferred from the kind of project itself? Because only when inside of a dpk the public API is kept even if not directly used.

**Comment by Cirras** [comment]
> Could this be inferred from the kind of project itself? Because only when inside of a dpk the public API is kept even if not directly used.

I see the appeal for the cut-and-dry library use case, but:
- It would be non-trivial to persist that information all the way through to the rules
- It would silently change the behavior of the analysis if the user didn't include their `.dpk` file in the source files for the scan
- Not all "libraries" actually take this shape. There are many large legacy codebases that have library-esque piles of shared code that they may wish to scan separately (and enable `excludeApi` for)

So I'd prefer the rule parameter approach.
