### ISSUE TITLE
Scan errors when defining a type with the same name of an imported unit

### ISSUE THREAD

**Issue by FLuzzi-csw** [integrated-application-development/sonar-delphi#161]
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.1.0

### SonarQube version

9.9.3

## Problem
When defining a `type` called the same as an imported library, `sonar-delphi` scan crashes.
This happens even if `sonar.delphi.unitScopeNames` is correctly populated.

## Expected
A rule catching this code smell
Related to #62

### Steps to reproduce

- Configure `sonar.delphi.unitScopeNames` to `WinApi`
- Execute a scan on this code snippet:
```pascal
uses
  Windows, // comment me when you uncomment "Winapi.Windows"
  //Winapi.Windows, -> uncomment me and the analysis will not crash
  System.SysUtils;

type
  TSample = class(TObject)
  private
  end;

  Windows = TSample;

begin
  try
    Writeln('Hello World!');
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
end.
```

- The execution will raise the exception:
  `au.com.integradev.delphi.symbol.scope.DuplicatedDeclarationException: Windows is already in the symbol table`

### Minimal Delphi code exhibiting the issue

[SonarQube_test.zip](https://github.com/integrated-application-development/sonar-delphi/files/13917240/SonarQube_test.zip)

Inside the zip there is a `sonar.log` file containing all the execution output in debug mode

**Comment by fourls** [comment]
Can confirm I encountered this today! From my initial analysis, it shouldn't be too tricky to fix.

**Comment by FLuzzi-csw** [comment]
What a coincidence!
Thanks for the fast response 👍
