### ISSUE TITLE
Scan error when a `const` is declared multiple times

### ISSUE THREAD

**Issue by FLuzzi-csw** [integrated-application-development/sonar-delphi#162]
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.1.0

### SonarQube version

9.9.3

## Problem
When reading parsing a project file defining the same `const` value multiple time, `sonar-delphi` scan crashes.

## Expected
I know this is a strange case, since the code doesn't even compile,
but i think it whould be best to add a rule catching this code as a `bug` instead of crashing 😄 

### Steps to reproduce

- Execute a scan on this code snippet:
```delphi
const
  test= 1;
  test= 2;

begin
  try
    Writeln('Hello World!');
  except
    on E: Exception do
      Writeln(E.ClassName, ': ', E.Message);
  end;
end.
```
- The execution will raise the exception:
  `au.com.integradev.delphi.symbol.scope.DuplicatedDeclarationException: test is already in the symbol table`

**Comment by Cirras** [comment]
I don't want to go out of our way to accept invalid Delphi code, or make the analyzer do the compiler's job by raising specific issues for compile-time errors.
