### ISSUE TITLE
Symbol table executor failure on include directives that include a symbol declaration and reference

### ISSUE THREAD

**Issue by fourls** [integrated-application-development/sonar-delphi#174]
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.1.0

### Issue description

The symbol table executor currently fails with an error in some cases when executing on files containing an include directive. Specifically, if the included code both declares and uses the same symbol, the executor complains that the declaration and reference for the given symbol are overlapping.

Note that this is not a parsing error, but an error with the symbol table executor, so the other executors still run (apart from the checks executor, which depends on the symbol table executor).

### Steps to reproduce

Scan the following code.

### Minimal Delphi code exhibiting the issue

```delphi
//////////// MyUnit.pas ////////////

unit MyUnit;

interface

{$I MyInclude.inc}

implementation

end.

////////// MyInclude.inc //////////

const
  Foo = 5;
  Bar = Foo + 10;
```

**Comment by fourls** [comment]
The simple approach would just be to silently ignore overlapping declarations and references. We could also adjust the way we treat included tokens, propagating their "included-ness" through to the symbolic nodes the symbol table executor is traversing so that we can implement some custom logic, but that would be a bit more in depth.

Interested to hear your thoughts on this @Cirras.

**Comment by Cirras** [comment]
We could do something rather heinous in `SonarSymbolTableVisitor::createSymbol` and try to look up the token based on the `SymbolicNode`'s token index.

Propagating the information through the symbolic nodes makes the most sense to me, though.
