### ISSUE TITLE
`DuplicatedDeclarationException` on inline variables in a `try` statement

### ISSUE THREAD

**Issue by Laurensvanrun** [integrated-application-development/sonar-delphi#220]
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.4.0

### SonarQube version

10.4.1

### Issue description

A `DuplicatedDeclarationException` exception occurs while parsing simple Delphi code where the same variable name is used twice in a `try..finally` or `try..except`. Once in the `try` and once in the `finally` or `except` block.

### Steps to reproduce

To reproduce this, you declare a variable in the `try`-block and use the same variablename in the `except`- or `finally`-block.

### Minimal Delphi code exhibiting the issue

``` delphi
procedure TMyClass.ThisCodeFails;
begin
  try
    var LVar := 'test';
  finally
    var LVar := 'test2';
  end;
end;

procedure TMyClass.ThisFailsToo;
begin
  try
    var LVar := 'test';
  except
    var LVar := 'test2';
  end;
end;
```

**Comment by Cirras** [comment]
Hi @Laurensvanrun,

Thanks!
I've confirmed that this is an issue with the way local scopes are created in the symbol table visitor.
