### ISSUE TITLE
Wrong report if `SysUtils.Format` has parameter with Upper-cased TYPE.

### ISSUE THREAD

**Issue by wdken** [integrated-application-development/sonar-delphi#228]
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.5.0

### SonarQube version

10.4

### Issue description

Using `SysUtils.Format` with Upper-cased TYPE reports wrong detection.
It was reported as "Fix this invalid format string.".

TYPE may be specified in uppercase as well as in lowercase; both produce the same results.
So this code has no problem.

It seems other TYPE in uppercase reports same wrong detection.

[https://docwiki.embarcadero.com/Libraries/Sydney/en/System.SysUtils.Format#Format_Strings](url)

### Steps to reproduce

Analysing the attached Delphi unit using Sonar-Delphi triggers this issue.

### Minimal Delphi code exhibiting the issue

~~~
function GetStr: string;
var
  ToBeShown: Integer;
begin
  ToBeShown := $12;
  Result := Format('%.4X', [ToBeShown]);  // this makes '0012'.  simular to "%.4x"
end;
~~~

**Comment by fourls** [comment]
Hi @wdken, thanks for raising this issue! You're totally correct, format strings are currently handled case-sensitively. I'll make a fix soon.
