### ISSUE TITLE
Option to report issue on "for" statement without for body

### ISSUE THREAD

**Issue by EduardoVaz06** [integrated-application-development/sonar-delphi#253]
### Prerequisites

- [X] This improvement has not already been suggested.
- [X] This improvement would be generally useful, not specific to my code or setup.

### Engine area

Rules API

### Improvement description

Provide a way to log issues on the "for" statement node, rather than the "for" body or the "for" variable, while iterating/visiting ForStatementNode, if there isn't already a way of doing so.

### Rationale

Currently, as far as I can tell, there is no way to raise an issue underlining only the `for` statement. I was creating a rule to check on nested for loops and wasn't able to raise the issue on the for statement itself. If there is already a way of doing that, I would appreciate to know how.

The rule I was creating is ralated to a business rule from my company, to check on nested for loops, visiting ForStatementNode `(visit(ForStatementNode forStatement, DelphiCheckContext context))`. Doing so, I could only get the ForStatementNode.getVariable() or the ForStatementNode itself / ForStatementNode.getStatement(), wich raises on the full body of the for.

* Example of issue being raised on the for body:
![NestedForFullStatement](https://github.com/integrated-application-development/sonar-delphi/assets/83786194/18c394ad-8fca-42fb-9708-c70180c01578)

* Example of issue being raised on the for variable:
![NestedForVariable](https://github.com/integrated-application-development/sonar-delphi/assets/83786194/330ecc3d-c9c2-4b25-a7a1-737645cd3424)

I think everyone could benefit from this addition, seeing that in for statements with more lines it could make issue raising more clear and specific in such cases.
![ForStatement](https://github.com/integrated-application-development/sonar-delphi/assets/83786194/88a0e7f1-33f4-4858-9aa8-bb5224e7ce7c)

**Comment by Cirras** [comment]
Hi @EduardoVaz06,

Agreed that this isn't the *most* intuitive, especially with the commonly-used `reportIssue` method only accepting a node for the location.

I believe that this is what you want:
```java
  @Override
  public DelphiCheckContext visit(ForStatementNode node, DelphiCheckContext context) {
    context.newIssue()
        .onFilePosition(FilePosition.from(node.getFirstToken()))
        .withMessage(MESSAGE);
    
    return super.visit(node, context);
  }
```

Can you let me know if that approach works as expected?

**Comment by EduardoVaz06** [comment]
Hi @Cirras, 

That's exactly what I wanted! Thanks for the answer and for helping.

One last thing, is that documented somewhere? If not, and you believe it would be a good thing, I would be glad to contribute by adding documentation about it.

**Comment by Cirras** [comment]
Glad to hear that this worked for you!
In general, we need to improve our javadoc coverage in the custom rules API.
This could have been a bit more discoverable if we had better documentation in `DelphiCheckContext`, `DelphiNode`, and `FilePosition`.
I'd be happy to accept PRs improving the documentation in those areas (and really anything in the custom files API).
