### ISSUE TITLE
Expression lexer failing to compile file in recursive directives

### ISSUE THREAD

**Issue by EduardoVaz06** [integrated-application-development/sonar-delphi#260]
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.6.0

### Issue description

An exception is raised in some delphi files while analyzing it, _au.integradev.delphi.preprocessor.directive.CompilerDirectiveParserImpl$CompilerDirectiveParserError: UNexpected character: '{'_ 

(CompilerDirectiveParserImpl.java) EXPRESSION_LEXER seems to not expect another directive and fails to compile the file.

![image](https://github.com/integrated-application-development/sonar-delphi/assets/83786194/86f9de87-a816-4b01-a799-e785871b192e)
![image](https://github.com/integrated-application-development/sonar-delphi/assets/83786194/6365f4d0-b74c-4f0a-be22-601b1714a97a)

Full exception on file: [exception-log.txt](https://github.com/user-attachments/files/15838485/exception-log.txt)

### Steps to reproduce

- Create directive that calls another directive recursively (like the example code below)

- Execute Sonar Scanner analysis with Sonar Delphi

- An exception should be raised in the file with the directive that calls another directive

### Minimal Delphi code exhibiting the issue

```
{$IF LicenseVersion <> {$I __version.txt}}
  {$Message Fatal 'Version different than the expected'}
{$ENDIF}
```

**Comment by Cirras** [comment]
Oh wow, I've literally never seen this kind of pattern before.
Good fun, we'll need to make some changes to the compiler directive parser to support this kind of nesting.

**Comment by denieu** [comment]
Explaining the use case a little better.

In the organization where I work we often use Git submodules as dependencies of our Delphi projects.

To add an extra layer of security, we add a __version.txt file in the submodule storing the dependency version (git tag name). In software that uses this submodule, we maintain a constant with the expected version and at compile time we check if the file __version.txt and the constant have the same value, if the value is different the software will not compile, forcing the developer to check why this happened.

Developers often updated the version of submodules by mistake, this strategy prevents this from being done unintentionally.

The strategy I mentioned is done through the code example brought by @EduardoVaz06.
