### ISSUE TITLE
Erroneous report for unused local variable

### ISSUE THREAD

**Issue by luebbe** [integrated-application-development/sonar-delphi#288]
Using the attached project the error occurs with every call to delphi-lint. RAD Studio 12.1. Delphi-lint version 1.8.0

But it really looks like it is related to VirtualTreeView, because the second method which basically does the same thing doesn't show the error. You have to add your path to VirtualTreeView to the project options.

![grafik](https://github.com/user-attachments/assets/124f4ee5-4c5e-4acb-821d-39c23fe668d0)

[UnusedVariableTest.zip](https://github.com/user-attachments/files/16714238/UnusedVariableTest.zip)

I've seen this also in other places in our code, which are not related to VST. I can try to find them and to extract an example. There are other similar reports about this issue. See: #108, #250.

_Originally posted by @luebbe in https://github.com/integrated-application-development/sonar-delphi/issues/211#issuecomment-2305028263_

**Comment by Cirras** [comment]
I can reproduce the false positive issue with this project - thanks!

> But it really looks like it is related to VirtualTreeView

VirtualTreeView is surely doing something that confuses the analyzer.
One point of interest is that `PVirtualNode` is a weak alias to a pointer type that points to an implicitly-forward-declared record type. It's an interesting set of conditions. I expect we're already handling that bit correctly, but I'll dig into it a bit to make sure.

> There are other similar reports about this issue. See: https://github.com/integrated-application-development/sonar-delphi/issues/108, https://github.com/integrated-application-development/sonar-delphi/issues/250.

This rule is the most likely to choke when there's a name resolution bug, so these other issues are really just different instances of name resolution bugs. It's a broad category, I'm guessing there's no relation to this issue.

**Comment by Cirras** [comment]
Hi @luebbe,

I've pinned this down to a very specific problem with the way we handle alias types in the analyzer's semantic model.
Name resolution was failing on `GetFirstSelected` because the name resolver was failing to traverse into the type scope of the `TVTAncestor` weak alias type.

Thanks again for your report - we'll get this fixed shortly.
