### ISSUE TITLE
Parsing error on semicolon-separated generic arguments in routine implementation

### ISSUE THREAD

**Issue by jgardn3r** [integrated-application-development/sonar-delphi#302]
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.10.0

### Issue description

There is a parsing error when consuming semicolon-separated generic arguments in a routine implementation. 

### Steps to reproduce

```delphi
type
  TFoo = class
    class procedure Bar<T; C>;
  end;

class procedure TFoo.Bar<T; C>; begin end;
```

**Comment by Cirras** [comment]
It's a problem with the way we model routine implementations names as "name references" in the grammar.
The type parameter list is using the type **argument** parsing rules as a consequence.
