### ISSUE TITLE
New Rule: Overloaded methods should not include both static and object level methods

### ISSUE THREAD

**Issue by Skarvion** [integrated-application-development/sonar-delphi#304]
### Prerequisites

- [X] This rule has not already been suggested.
- [X] This should be a new rule, not an improvement to an existing rule.
- [X] This rule would be generally useful, not specific to my code or setup.

### Suggested rule title

Overloaded methods should not include both static and object level methods

### Rule description

No overloaded methods of the same name should include both of object and static methods. This makes it hard to distinguish their method level.

### Rationale

Sample of non-compliant declaration

```delphi
type
  TFoo = class(TObject)
  public
    class procedure Bar; overload;
    procedure Bar(Param: String); overload;
  end;
```

**Comment by Cirras** [comment]
Hi @Skarvion,
After some discussion, we've decided against this rule.
It's a bit subjective, a bit specific, and probably not worth the effort to implement/maintain due to how uncommon a pattern it is.
