### ISSUE TITLE
EXECUTION FAILURE on execute

### ISSUE THREAD

**Issue by viniciuspoletto** [integrated-application-development/sonar-delphi#306]
### Prerequisites

- [X] This question has not already been answered.
- [X] This question is about SonarDelphi, not SonarQube or Delphi.

### Inquiry

Hello, I am trying use de plugin but I have a failure. The console output is:

10:12:11.726 INFO  Scanner configuration file: C:\sonar-scanner\bin\..\conf\sonar-scanner.properties
10:12:11.731 INFO  Project root configuration file: E:\Vini\Desbravador\Sonar\Delphi\sonar-project.properties
10:12:11.757 INFO  SonarScanner CLI 6.2.1.4610
10:12:11.759 INFO  Java 17.0.12 Eclipse Adoptium (64-bit)
10:12:11.761 INFO  Windows 10 10.0 amd64
10:12:11.772 DEBUG Scanner max available memory: 1 GB
10:12:11.796 DEBUG Create: C:\Users\vinic\.sonar\cache
10:12:11.797 INFO  User cache: C:\Users\vinic\.sonar\cache
10:12:11.797 DEBUG Create: C:\Users\vinic\.sonar\cache\_tmp
10:12:12.044 DEBUG Successfully loaded KeyStore of the type [Windows-ROOT] having [43] entries
10:12:12.044 DEBUG Failed to load KeyStore of the type [Windows-ROOT-LOCALMACHINE]
10:12:12.088 DEBUG Successfully loaded KeyStore of the type [Windows-ROOT-CURRENTUSER] having [43] entries
10:12:12.089 DEBUG Successfully loaded KeyStore of the type [Windows-MY] having [0] entries
10:12:12.090 DEBUG Successfully loaded KeyStore of the type [Windows-MY-CURRENTUSER] having [0] entries
10:12:12.090 DEBUG Failed to load KeyStore of the type [Windows-MY-LOCALMACHINE]
10:12:12.092 DEBUG Loaded [86] system trusted certificates
10:12:12.413 DEBUG --> GET http://localhost:9000/api/v2/analysis/version
10:12:12.613 DEBUG <-- 200 http://localhost:9000/api/v2/analysis/version (200ms, 12-byte body)
10:12:12.616 INFO  JRE provisioning: os[windows], arch[amd64]
10:12:12.620 DEBUG --> GET http://localhost:9000/api/v2/analysis/jres?os=windows&arch=amd64
10:12:12.708 DEBUG <-- 200 http://localhost:9000/api/v2/analysis/jres?os=windows&arch=amd64 (87ms, unknown-length body)
10:12:12.784 DEBUG Executing: C:\Users\vinic\.sonar\cache\4bafe2e94439c8193fc8c68247cb0dbaf4e80265b903288f63f128304f129bbe\OpenJDK17U-jre_x64_windows_hotspot_17.0.11_9.zip_extracted\jdk-17.0.11+9-jre\bin\java.exe --version
10:12:12.983 DEBUG openjdk 17.0.11 2024-04-16
10:12:12.983 DEBUG OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
10:12:12.984 DEBUG OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode, sharing)
10:12:13.009 DEBUG --> GET http://localhost:9000/api/v2/analysis/engine
10:12:13.474 DEBUG <-- 200 http://localhost:9000/api/v2/analysis/engine (464ms, unknown-length body)
10:12:13.477 INFO  Communicating with SonarQube Server 10.7.0.96327
10:12:13.478 DEBUG Work directory: E:\Vini\Desbravador\Sonar\Delphi\.scannerwork
10:12:13.488 DEBUG Executing: C:\Users\vinic\.sonar\cache\4bafe2e94439c8193fc8c68247cb0dbaf4e80265b903288f63f128304f129bbe\OpenJDK17U-jre_x64_windows_hotspot_17.0.11_9.zip_extracted\jdk-17.0.11+9-jre\bin\java.exe -jar C:\Users\vinic\.sonar\cache\d5653c126135ff7d09813343eecfaa5f971529fd7e75aa30085a33bd426a5c6c\sonar-scanner-engine-shaded-10.7.0.96327-all.jar
10:12:14.004 INFO  Starting SonarScanner Engine...
10:12:14.005 INFO  Java 17.0.11 Eclipse Adoptium (64-bit)
10:12:14.050 DEBUG JVM max available memory: 1 GB
10:12:14.266 DEBUG Community 10.7.0.96327
10:12:14.443 DEBUG Sonar User Home: C:\Users\vinic\.sonar
10:12:14.713 DEBUG Successfully loaded KeyStore of the type [Windows-ROOT] having [43] entries
10:12:14.715 DEBUG Failed to load KeyStore of the type [Windows-ROOT-LOCALMACHINE]
10:12:14.764 DEBUG Successfully loaded KeyStore of the type [Windows-ROOT-CURRENTUSER] having [43] entries
10:12:14.766 DEBUG Successfully loaded KeyStore of the type [Windows-MY] having [0] entries
10:12:14.767 DEBUG Successfully loaded KeyStore of the type [Windows-MY-CURRENTUSER] having [0] entries
10:12:14.767 DEBUG Failed to load KeyStore of the type [Windows-MY-LOCALMACHINE]
10:12:14.769 DEBUG Loaded [86] system trusted certificates
10:12:15.066 INFO  Load global settings
10:12:15.083 DEBUG --> GET http://localhost:9000/api/settings/values.protobuf
10:12:15.229 DEBUG <-- 200 http://localhost:9000/api/settings/values.protobuf (146ms, 7080-byte body)
10:12:15.272 INFO  Load global settings (done) | time=204ms
10:12:15.277 INFO  Server id: 147B411E-AZJcbIqbWyey2N4mn4fl
10:12:15.286 DEBUG User cache: C:\Users\vinic\.sonar\cache
10:12:15.298 INFO  Loading required plugins
10:12:15.301 INFO  Load plugins index
10:12:15.304 DEBUG --> GET http://localhost:9000/api/plugins/installed
10:12:15.464 DEBUG <-- 200 http://localhost:9000/api/plugins/installed (157ms, unknown-length body)
10:12:15.473 INFO  Load plugins index (done) | time=173ms
10:12:15.474 INFO  Load/download plugins
10:12:15.543 INFO  Load/download plugins (done) | time=69ms
10:12:15.544 DEBUG Plugins not loaded because they are optional: [csharp, communitydelphi, flex, go, web, javasymbolicexecution, java, javascript, kotlin, php, python, ruby, sonarscala, vbnet]
10:12:15.568 DEBUG Plugins loaded:
10:12:15.569 DEBUG   * JaCoCo 1.3.0.1538 (jacoco)
10:12:15.570 DEBUG   * IaC Code Quality and Security 1.36.0.12431 (iac)
10:12:15.570 DEBUG   * Text Code Quality and Security 2.16.0.4008 (text)
10:12:15.571 DEBUG   * Clean as You Code 2.4.0.2018 (cayc)
10:12:15.572 DEBUG   * XML Code Quality and Security 2.10.0.4108 (xml)
10:12:15.813 DEBUG register org.eclipse.jgit.util.FS$FileStoreAttributes$$Lambda$336/0x000001a40125d608@5f212d84 with shutdown hook
10:12:16.011 INFO  Process project properties
10:12:16.028 INFO  Process project properties (done) | time=18ms
10:12:16.050 INFO  Project key: Calculadora
10:12:16.052 INFO  Base dir: E:\Vini\Desbravador\Sonar\Delphi
10:12:16.053 INFO  Working dir: E:\Vini\Desbravador\Sonar\Delphi\.scannerwork
10:12:16.054 DEBUG Project global encoding: windows-1252, default locale: pt_BR
10:12:16.071 INFO  Load project settings for component key: 'Calculadora'
10:12:16.076 DEBUG --> GET http://localhost:9000/api/settings/values.protobuf?component=Calculadora
10:12:16.223 DEBUG <-- 200 http://localhost:9000/api/settings/values.protobuf?component=Calculadora (141ms, 7086-byte body)
10:12:16.223 INFO  Load project settings for component key: 'Calculadora' (done) | time=152ms
10:12:16.280 DEBUG Creating module hierarchy
10:12:16.283 DEBUG   Init module 'Calculadora'
10:12:16.290 DEBUG     Base dir: E:\Vini\Desbravador\Sonar\Delphi
10:12:16.290 DEBUG     Working dir: E:\Vini\Desbravador\Sonar\Delphi\.scannerwork
10:12:16.294 DEBUG     Module global encoding: windows-1252, default locale: pt_BR
10:12:16.324 INFO  Load quality profiles
10:12:16.327 DEBUG --> GET http://localhost:9000/api/qualityprofiles/search.protobuf?project=Calculadora
10:12:16.723 DEBUG <-- 200 http://localhost:9000/api/qualityprofiles/search.protobuf?project=Calculadora (394ms, 3167-byte body)
10:12:16.761 INFO  Load quality profiles (done) | time=436ms
10:12:16.871 DEBUG SCM Step is disabled by configuration
10:12:16.892 INFO  Load active rules
10:12:16.894 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=ebfc33af-79f8-4f9b-bf06-52c9be193e48&ps=500&p=1
10:12:17.466 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=ebfc33af-79f8-4f9b-bf06-52c9be193e48&ps=500&p=1 (568ms, 7151-byte body)
10:12:17.816 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=85fc2ee3-458c-4c5a-842a-52f57ae37a94&ps=500&p=1
10:12:18.051 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=85fc2ee3-458c-4c5a-842a-52f57ae37a94&ps=500&p=1 (231ms, unknown-length body)
10:12:18.066 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=b67d9fa4-c7b0-45dd-b8cb-7d2bc78bb3ad&ps=500&p=1
10:12:18.377 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=b67d9fa4-c7b0-45dd-b8cb-7d2bc78bb3ad&ps=500&p=1 (309ms, unknown-length body)
10:12:18.382 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=286b8cdc-bcd7-4719-982f-e522d8429205&ps=500&p=1
10:12:18.408 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=286b8cdc-bcd7-4719-982f-e522d8429205&ps=500&p=1 (23ms, 12-byte body)
10:12:18.408 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=06eca81d-48bf-436b-94dc-1536a72d0f24&ps=500&p=1
10:12:20.025 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=06eca81d-48bf-436b-94dc-1536a72d0f24&ps=500&p=1 (1614ms, unknown-length body)
10:12:20.194 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=f429c68c-c498-44a6-a158-6cc096953d9c&ps=500&p=1
10:12:21.119 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=f429c68c-c498-44a6-a158-6cc096953d9c&ps=500&p=1 (918ms, unknown-length body)
10:12:21.163 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=b88af580-8a3f-41ab-8663-03eaf77a4212&ps=500&p=1
10:12:21.420 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=b88af580-8a3f-41ab-8663-03eaf77a4212&ps=500&p=1 (252ms, unknown-length body)
10:12:21.421 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=b97df02c-d659-473a-981c-72fc512ffbc9&ps=500&p=1
10:12:22.679 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=b97df02c-d659-473a-981c-72fc512ffbc9&ps=500&p=1 (1256ms, unknown-length body)
10:12:22.778 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=b97df02c-d659-473a-981c-72fc512ffbc9&ps=500&p=2
10:12:22.898 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=b97df02c-d659-473a-981c-72fc512ffbc9&ps=500&p=2 (119ms, 3791-byte body)
10:12:22.904 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=64f00796-d61c-40a3-ae7a-ac17e75a34a9&ps=500&p=1
10:12:23.083 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=64f00796-d61c-40a3-ae7a-ac17e75a34a9&ps=500&p=1 (179ms, unknown-length body)
10:12:23.094 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=feaea506-df03-4847-9a1b-7594e87cab62&ps=500&p=1
10:12:23.196 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=feaea506-df03-4847-9a1b-7594e87cab62&ps=500&p=1 (101ms, unknown-length body)
10:12:23.197 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=0c90441a-c8b0-4448-b6a6-415f2713d6d9&ps=500&p=1
10:12:23.308 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=0c90441a-c8b0-4448-b6a6-415f2713d6d9&ps=500&p=1 (106ms, 7249-byte body)
10:12:23.309 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=11a01bb3-1311-4ecb-a81f-ba24c83f08bd&ps=500&p=1
10:12:23.322 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=11a01bb3-1311-4ecb-a81f-ba24c83f08bd&ps=500&p=1 (15ms, 12-byte body)
10:12:23.324 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=82022f16-455a-49aa-90db-1c8ced68f3d9&ps=500&p=1
10:12:24.060 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=82022f16-455a-49aa-90db-1c8ced68f3d9&ps=500&p=1 (736ms, unknown-length body)
10:12:24.075 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=a65afa89-581d-4904-8a19-cd15ef449bdd&ps=500&p=1
10:12:24.107 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=a65afa89-581d-4904-8a19-cd15ef449bdd&ps=500&p=1 (30ms, 358-byte body)
10:12:24.107 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=59667095-5545-4f8f-ab1f-f456712a4879&ps=500&p=1
10:12:24.575 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=59667095-5545-4f8f-ab1f-f456712a4879&ps=500&p=1 (470ms, unknown-length body)
10:12:24.583 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=f8f572cc-3b50-41b4-b517-cc89aeaec74c&ps=500&p=1
10:12:24.683 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=f8f572cc-3b50-41b4-b517-cc89aeaec74c&ps=500&p=1 (99ms, unknown-length body)
10:12:24.685 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=3706d490-d4ae-4849-927d-39a5e7e3ec8a&ps=500&p=1
10:12:24.697 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=3706d490-d4ae-4849-927d-39a5e7e3ec8a&ps=500&p=1 (10ms, 12-byte body)
10:12:24.697 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=07d08934-e62e-42f1-b206-5eccc4741142&ps=500&p=1
10:12:24.936 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=07d08934-e62e-42f1-b206-5eccc4741142&ps=500&p=1 (238ms, unknown-length body)
10:12:24.941 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=3e158a9b-3625-40d4-8f1e-750626ba2331&ps=500&p=1
10:12:25.002 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=3e158a9b-3625-40d4-8f1e-750626ba2331&ps=500&p=1 (58ms, 7691-byte body)
10:12:25.003 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=2000f434-5de8-48db-803f-1fc155d3d006&ps=500&p=1
10:12:25.290 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=2000f434-5de8-48db-803f-1fc155d3d006&ps=500&p=1 (286ms, unknown-length body)
10:12:25.296 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=fcc304e5-3944-416c-a732-f3a941e03683&ps=500&p=1
10:12:25.593 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=fcc304e5-3944-416c-a732-f3a941e03683&ps=500&p=1 (291ms, unknown-length body)
10:12:25.598 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=b3210bc2-5a73-4a06-8c4d-7307a3c5b19e&ps=500&p=1
10:12:25.662 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=b3210bc2-5a73-4a06-8c4d-7307a3c5b19e&ps=500&p=1 (64ms, unknown-length body)
10:12:25.666 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=62bf46ac-bb6a-4ae5-89b6-add6fb43012f&ps=500&p=1
10:12:26.404 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=62bf46ac-bb6a-4ae5-89b6-add6fb43012f&ps=500&p=1 (736ms, unknown-length body)
10:12:26.424 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=80d0fce5-ae9a-45cb-a466-5ec55589dbf5&ps=500&p=1
10:12:26.812 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=80d0fce5-ae9a-45cb-a466-5ec55589dbf5&ps=500&p=1 (388ms, unknown-length body)
10:12:26.820 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=89295aca-0ccd-47c6-9c50-666583753ba1&ps=500&p=1
10:12:27.047 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=89295aca-0ccd-47c6-9c50-666583753ba1&ps=500&p=1 (226ms, unknown-length body)
10:12:27.050 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=0500285c-549a-4662-8296-9170eaf04bb9&ps=500&p=1
10:12:27.198 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=0500285c-549a-4662-8296-9170eaf04bb9&ps=500&p=1 (148ms, unknown-length body)
10:12:27.200 DEBUG --> GET http://localhost:9000/api/rules/list.protobuf?qprofile=585c3a54-8e8a-4101-a4f3-fdc7ee15bc2b&ps=500&p=1
10:12:28.091 DEBUG <-- 200 http://localhost:9000/api/rules/list.protobuf?qprofile=585c3a54-8e8a-4101-a4f3-fdc7ee15bc2b&ps=500&p=1 (877ms, unknown-length body)
10:12:28.126 INFO  Load active rules (done) | time=11235ms
10:12:28.152 INFO  Load analysis cache
10:12:28.154 DEBUG --> GET http://localhost:9000/api/analysis_cache/get?project=Calculadora
10:12:28.186 DEBUG <-- 404 http://localhost:9000/api/analysis_cache/get?project=Calculadora (32ms, unknown-length body)
10:12:28.195 INFO  Load analysis cache (404) | time=41ms
10:12:28.266 DEBUG --> GET http://localhost:9000/api/languages/list
10:12:28.275 DEBUG <-- 200 http://localhost:9000/api/languages/list (8ms, unknown-length body)
10:12:28.349 DEBUG Declared patterns of language Kubernetes were converted to sonar.lang.patterns.kubernetes : 
10:12:28.352 DEBUG Declared patterns of language CSS were converted to sonar.lang.patterns.css : **/*.css,**/*.less,**/*.scss,**/*.sass
10:12:28.353 DEBUG Declared patterns of language Scala were converted to sonar.lang.patterns.scala : **/*.scala
10:12:28.354 DEBUG Declared patterns of language JSP were converted to sonar.lang.patterns.jsp : **/*.jsp,**/*.jspf,**/*.jspx
10:12:28.356 DEBUG Declared patterns of language JavaScript were converted to sonar.lang.patterns.js : **/*.js,**/*.jsx,**/*.cjs,**/*.mjs,**/*.vue
10:12:28.358 DEBUG Declared patterns of language Python were converted to sonar.lang.patterns.py : **/*.py
10:12:28.359 DEBUG Declared patterns of language Docker were converted to sonar.lang.patterns.docker : **/Dockerfile,**/*.dockerfile
10:12:28.360 DEBUG Declared patterns of language Java were converted to sonar.lang.patterns.java : **/*.java,**/*.jav
10:12:28.363 DEBUG Declared patterns of language HTML were converted to sonar.lang.patterns.web : **/*.html,**/*.xhtml,**/*.cshtml,**/*.vbhtml,**/*.aspx,**/*.ascx,**/*.rhtml,**/*.erb,**/*.shtm,**/*.shtml,**/*.cmp,**/*.twig
10:12:28.367 DEBUG Declared patterns of language Flex were converted to sonar.lang.patterns.flex : **/*.as
10:12:28.372 DEBUG Declared patterns of language XML were converted to sonar.lang.patterns.xml : **/*.xml,**/*.xsd,**/*.xsl,**/*.config
10:12:28.379 DEBUG Declared patterns of language JSON were converted to sonar.lang.patterns.json : **/*.json
10:12:28.380 DEBUG Declared patterns of language IPython Notebooks were converted to sonar.lang.patterns.ipynb : **/*.ipynb
10:12:28.383 DEBUG Declared patterns of language Text were converted to sonar.lang.patterns.text : 
10:12:28.385 DEBUG Declared patterns of language VB.NET were converted to sonar.lang.patterns.vbnet : **/*.vb
10:12:28.385 DEBUG Declared patterns of language CloudFormation were converted to sonar.lang.patterns.cloudformation : 
10:12:28.387 DEBUG Declared patterns of language YAML were converted to sonar.lang.patterns.yaml : **/*.yaml,**/*.yml
10:12:28.392 DEBUG Declared patterns of language Delphi were converted to sonar.lang.patterns.delphi : **/*.pas,**/*.dpr,**/*.dpk
10:12:28.394 DEBUG Declared patterns of language Go were converted to sonar.lang.patterns.go : **/*.go
10:12:28.396 DEBUG Declared patterns of language Kotlin were converted to sonar.lang.patterns.kotlin : **/*.kt,**/*.kts
10:12:28.397 DEBUG Declared patterns of language Secrets were converted to sonar.lang.patterns.secrets : 
10:12:28.398 DEBUG Declared patterns of language Ruby were converted to sonar.lang.patterns.ruby : **/*.rb
10:12:28.399 DEBUG Declared patterns of language C# were converted to sonar.lang.patterns.cs : **/*.cs,**/*.razor
10:12:28.399 DEBUG Declared patterns of language PHP were converted to sonar.lang.patterns.php : **/*.php,**/*.php3,**/*.php4,**/*.php5,**/*.phtml,**/*.inc
10:12:28.400 DEBUG Declared patterns of language Terraform were converted to sonar.lang.patterns.terraform : **/*.tf
10:12:28.401 DEBUG Declared patterns of language AzureResourceManager were converted to sonar.lang.patterns.azureresourcemanager : **/*.bicep
10:12:28.401 DEBUG Declared patterns of language TypeScript were converted to sonar.lang.patterns.ts : **/*.ts,**/*.tsx,**/*.cts,**/*.mts
10:12:28.422 INFO  Preprocessing files...
10:12:28.479 INFO  1 language detected in 3 preprocessed files
10:12:28.480 INFO  9 files ignored because of inclusion/exclusion patterns
10:12:28.483 INFO  Loading plugins for detected languages
10:12:28.484 DEBUG Detected languages: [delphi]
10:12:28.485 INFO  Load/download plugins
10:12:28.513 INFO  Load/download plugins (done) | time=27ms
10:12:28.513 DEBUG Optional language-specific plugins not loaded: [csharp, flex, go, web, javasymbolicexecution, java, javascript, kotlin, php, python, ruby, sonarscala, vbnet]
10:12:28.521 DEBUG Plugins loaded:
10:12:28.521 DEBUG   * Delphi 1.10.0 (communitydelphi)
10:12:28.668 INFO  Load project repositories
10:12:28.669 DEBUG --> GET http://localhost:9000/batch/project.protobuf?key=Calculadora
10:12:28.703 DEBUG <-- 200 http://localhost:9000/batch/project.protobuf?key=Calculadora (33ms, 0-byte body)
10:12:28.730 INFO  Load project repositories (done) | time=43ms
10:12:28.743 DEBUG Available languages:
10:12:28.743 DEBUG   * Delphi => "delphi"
10:12:28.744 DEBUG   * Terraform => "terraform"
10:12:28.744 DEBUG   * CloudFormation => "cloudformation"
10:12:28.744 DEBUG   * Kubernetes => "kubernetes"
10:12:28.744 DEBUG   * Docker => "docker"
10:12:28.745 DEBUG   * AzureResourceManager => "azureresourcemanager"
10:12:28.745 DEBUG   * YAML => "yaml"
10:12:28.745 DEBUG   * JSON => "json"
10:12:28.745 DEBUG   * Text => "text"
10:12:28.746 DEBUG   * Secrets => "secrets"
10:12:28.746 DEBUG   * XML => "xml"
10:12:28.748 INFO  Indexing files...
10:12:28.749 INFO  Project configuration:
10:12:28.750 INFO    Included sources: **/*.dpr, **/*.pas, **/*.dproj
10:12:28.768 DEBUG 'calc\Calculadora.dpr' indexed with language 'delphi'
10:12:28.790 DEBUG 'calc\Calculadora.dproj' indexed with no language
10:12:28.792 DEBUG 'calc\Unit1.pas' indexed with language 'delphi'
10:12:28.796 INFO  3 files indexed
10:12:28.797 INFO  Quality profile for delphi: Sonar way
10:12:28.798 INFO  ------------- Run sensors on module Calculadora
10:12:28.881 INFO  Load metrics repository
10:12:28.884 DEBUG --> GET http://localhost:9000/api/metrics/search?ps=500&p=1
10:12:28.908 DEBUG <-- 200 http://localhost:9000/api/metrics/search?ps=500&p=1 (22ms, unknown-length body)
10:12:28.954 INFO  Load metrics repository (done) | time=73ms
10:12:29.726 DEBUG 'Import external issues report' skipped because one of the required properties is missing
10:12:29.730 DEBUG 'IaC Terraform Sensor' skipped because there is no related file in current project
10:12:29.731 DEBUG 'IaC CloudFormation Sensor' skipped because there is no related file in current project
10:12:29.733 DEBUG 'IaC Kubernetes Sensor' skipped because there is no related file in current project
10:12:29.734 DEBUG 'IaC AzureResourceManager Sensor' skipped because there is no related file in current project
10:12:29.736 DEBUG 'XML Sensor' skipped because there is no related file in current project
10:12:29.744 DEBUG 'Generic Test Executions Report' skipped because one of the required properties is missing
10:12:29.747 DEBUG Sensors : JaCoCo XML Report Importer -> Java Config Sensor -> DelphiSensor -> DelphiCoverageSensor -> Delphi NUnit Sensor -> IaC Docker Sensor -> TextAndSecretsSensor
10:12:29.749 INFO  Sensor JaCoCo XML Report Importer [jacoco]
10:12:29.752 INFO  'sonar.coverage.jacoco.xmlReportPaths' is not defined. Using default locations: target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml,build/reports/jacoco/test/jacocoTestReport.xml
10:12:29.754 INFO  No report imported, no coverage information will be imported by JaCoCo XML Report Importer
10:12:29.755 INFO  Sensor JaCoCo XML Report Importer [jacoco] (done) | time=7ms
10:12:29.756 INFO  Sensor Java Config Sensor [iac]
10:12:29.796 INFO  0 source files to be analyzed
10:12:29.805 INFO  0/0 source files have been analyzed
10:12:29.805 INFO  Sensor Java Config Sensor [iac] (done) | time=48ms
10:12:29.806 INFO  Sensor DelphiSensor [communitydelphi]
10:12:29.806 INFO  Platform: WINDOWS
10:12:29.806 INFO  Architecture: X86
10:12:29.806 INFO  Compiler version: 35.0
10:12:29.809 INFO  Indexing 1 dproj file(s) and 0 groupproj file(s)...
10:12:29.994 INFO  Conditional defines: [ASSEMBLER, DCC, CPU386, CPUX86, UNICODE, DEBUG, MSWINDOWS, CPU32BITS, NATIVECODE, CONSOLE, WIN32, VER350, UNDERSCOREIMPORTNAME, CONDITIONALEXPRESSIONS]
10:12:31.867 DEBUG Cleanup org.eclipse.jgit.util.FS$FileStoreAttributes$$Lambda$336/0x000001a40125d608@5f212d84 during JVM shutdown
10:12:31.945 DEBUG Java command exited with code 1
10:12:31.945 INFO  EXECUTION FAILURE
10:12:31.947 INFO  Total time: 20.225s

The Delphi project and sonar-project.properties are attached. I am using RunScannerSonar.bat to call sonarqube.

my e-mail is: viniciuspoletto@hotmail.com

Can you help me?
[Delphi_project.zip](https://github.com/user-attachments/files/17445345/Delphi_project.zip)

**Comment by zaneduffield** [comment]
Hi @viniciuspoletto, I think your logging output is incomplete; the `.bat` file provided in the archive only redirects stdout to the file, but error output from the sonar-scanner is sent to stderr.

I would expect some kind of stacktrace or error logging before reporting 'execution failure'.

If you append `2>&1` to the *end* of the command in `RunScannerSonar.bat` then the file should contain the error logging. Your project scans without errors for me, so I suspect that the problem is some kind of configuration issue, which the extra logging should illuminate.

If you still can't figure out what's causing the scan to fail feel free to open a new issue with the extra error logging.

**Comment by viniciuspoletto** [comment]
Hello, Thanks for your response. I removed de output file than I saw that the Delphi directory was incorrect. SonaQube has 22.0 version as default and I am using 23.0 version.

Thanks again
