### ISSUE TITLE
New rule: Sequential sections of the same type should be merged

### ISSUE THREAD

**Issue by fourls** [integrated-application-development/sonar-delphi#65]
### Prerequisites

- [X] This rule has not already been suggested.
- [X] This should be a new rule, not an improvement to an existing rule.
- [X] This rule would be generally useful, not specific to my code or setup.

### Suggested rule title

Sequential sections of the same type should be merged

### Rule description

It would detect sequential blocks/sections of the same type, including

- `var` blocks
- `const` blocks
- visibility sections

For example:

```delphi
type
  TFoo = class(TObject)
  private
    FName: string;
  private // Noncompliant
    FAge: Integer;
    procedure Bar;
  public
    procedure Baz;
  end;
```

```delphi
type
  TFoo = class(TObject)
  private // Compliant
    FName: string;
    FAge: Integer;
    procedure Bar;
  public
    procedure Baz;
  end;
```

### Rationale

When two identical blocks are non-sequential, there's a solid chance that there could be a reason - e.g. defining a constant, variable, or property that is used in later sections - but when they are sequential, having the two sections separate is pointless and harms readability.

If the behaviour of this rule is a little overloaded, it could also be split into different sub-rules for different types of section?

**Comment by Cirras** [comment]
> If the behaviour of this rule is a little overloaded, it could also be split into different sub-rules for different types of section?

I think separate sub-rules are the way to go on this one.
What do you suppose the full list of rules would look like?

**Comment by fourls** [comment]
> I think separate sub-rules are the way to go on this one. What do you suppose the full list of rules would look like?

I believe it could probably be split into four rules:

- SequentialVarSection
- SequentialConstSection
- SequentialTypeSection
- SequentialVisibilitySection

Those are the four types of sections that can be freely placed after another instance of itself AFAIK.

**Comment by Cirras** [comment]
Sounds good.
Due to their similarity, I'm happy for this issue (and any resulting PR) to just bundle them all together.

**Comment by fourls** [comment]
I imagine they might even have an abstract base class they all inherit from. Of course, depends on how the implementation ends up working.
