### ISSUE TITLE
[New Rule]: Unused default parameters should be removed

### ISSUE THREAD

**Issue by fourls** [integrated-application-development/sonar-delphi#68]
### Prerequisites

- [X] This rule has not already been suggested.
- [X] This should be a new rule, not an improvement to an existing rule.
- [X] This rule would be generally useful, not specific to my code or setup.

### Suggested rule title

Unused default parameters should be removed

### Rule description

This rule would identify methods with a default parameter that is not expressed in any of its calls.

As an extension, this rule could also identify methods with a default parameter that is only ever set to its default value.

### Rationale

Default parameters can be used to add a lot of unnecessary cruft to an API, and are confusing and unintuitive to read. Default parameters that are never actually utilised complicate a method's signature at no benefit and should be removed.

It is very difficult to statically verify whether a default parameter is used or not without something like SonarDelphi, and removing them has a major affect on maintainability and readability.

**Comment by Cirras** [comment]
The rule would look like this:
* From a given method declaration...
   * Iterate each occurrence of the declaration
   * (Somehow?) check the number of arguments passed to the method at that name occurrence
   * Raise an issue of the number of arguments has always been >= the index of the default parameter, meaning the argument has always been provided.

I'm not immediately sure how best to represent this argument data in the symbol API.
Thoughts?

**Comment by fourls** [comment]
I tried to do this as a quick thing a few weeks ago and came up against the same design issue. The big problem is not being able to reason about any detail of the name occurrences.

I toyed with the idea of giving name occurrences more context, e.g. number of arguments. 
I don't think it's a bad idea, but it's a bit of a slippery slope adding to the API for the benefit of a single rule, though.

**Comment by Cirras** [comment]
I'm of two minds:
* leave it open and forget about this issue for now, acknowledging it's in the bucket of "needs engine improvements"
* close the issue and reopen it if we ever add invocation data to the `symbol` API
(since it's not a guaranteed engine improvement)

What do you think @fourls?

**Comment by fourls** [comment]
Maybe let's close it for now - it's not feasible in the project's current state. We could raise a new "Engine Improvement" issue for adding more data on invocations to the symbol API?

**Comment by Cirras** [comment]
> Maybe let's close it for now - it's not feasible in the project's current state.

Alright, we'll go that route.

> We could raise a new "Engine Improvement" issue for adding more data on invocations to the symbol API?

Sure - no rush, let's give some thought to what that API extension should look like.
