### ISSUE TITLE
[New Rule]: Top-level type names should not be duplicated

### ISSUE THREAD

**Issue by fourls** [integrated-application-development/sonar-delphi#70]
### Prerequisites

- [x] This rule has not already been suggested.
- [x] This should be a new rule, not an improvement to an existing rule.
- [x] This rule would be generally useful, not specific to my code or setup.

### Rule description

This rule would identify instances where two top-level types have the same unqualified name. This could be

* Two types in the same implementation section
* Two types in the same interface section
* One type in the interface section and one type in the implementation section of the same unit
* One type in the interface section and one type in the implementation section of a different unit
* Two types in the interface section of different units

### Rationale

Although allowed, it's generally frowned upon to have two types with the same name in a project. It can result in accidental issues where an identifier resolves to an unexpected type, and makes code much less readable.

**Comment by Cirras** [comment]
> * Two types in the same implementation section
> * Two types in the same interface section
> * One type in the interface section and one type in the implementation section of the same unit

This doesn't seem to be possible.
![image](https://github.com/integrated-application-development/sonar-delphi/assets/22178573/3a9de9ad-41be-48b9-aaca-d14e267b87d6)

That just leaves:
> * One type in the interface section and one type in the implementation section of a different unit
> * Two types in the interface section of different units

One thing I don't like about these types of "project-level" rules is when there isn't a clear target. Are we going to somehow deterministically pick which type to flag?
Flag both, even?

The lack of locality here kind of hurts the strength of the proposal, in my opinion.

**Comment by Cirras** [comment]
Another question, would we be including dependencies like the standard library or things on the search path?

At that point, it would kind of turn into "don't ever shadow anything!"

**Comment by fourls** [comment]
> This doesn't seem to be possible.

Good catch, for some reason I thought it was.

> One thing I don't like about these types of "project-level" rules is when there isn't a clear target for the issue. Are we going to somehow deterministically pick which type to flag?
> Flag both, even?

I think flag both. As you say, they're both equally violating the rule. Doing so would also make the implementation easier as it can be stateless.

> Another question, would we be including dependencies like the standard library or things on the search path?

This could perhaps be configurable? I think the default should be NO, only types in the source files.

**Comment by Cirras** [comment]
> I think flag both

Hmm. I don't like reporting issues that are likely to blame the wrong person - and an issue raised on the original type declaration surely would.

At the same time, there's no *good* way for the plugin to say "yep, this one came first!"
Even if there was, we wouldn't want to store that information in the semantic model.

Purely from this perspective, the rule may be too much of a headache.

Let's close this issue for now and reconsider it if there's some new angle on how it could be implemented.
