### ISSUE TITLE
Support multiline string syntax

### ISSUE THREAD

**Issue by fourls** [integrated-application-development/sonar-delphi#80]
### Prerequisites

- [X] This improvement has not already been suggested.
- [X] This improvement would be generally useful, not specific to my code or setup.

### Engine area

Delphi language support

### Improvement description

Delphi 12 supports multiline strings using triple quotes (`'''`) as follows:

* The closing `'''` must be on a line of its own.
* The indentation of the closing `'''` determines the base indentation of the entire string.
* None of the lines can be less indented than the base indentation.
* The last newline before the closing `'''` is omitted.
* Any odd number of quotes can be used, to allow the inclusion of triple quotes in the string text.

For more details, see the [official documentation](https://docwiki.embarcadero.com/RADStudio/Athens/en/String_Types_(Delphi)#Long_and_Multiline_String_Literals) and [Marco Cantu's blog post introducing the feature](https://blogs.embarcadero.com/yukon-beta-blog-delphi-language-modernizing-string-literals/).

### Rationale

This is required to parse Delphi 12 code.

**Comment by zaneduffield** [comment]
Also note that the documentation is currently lacking the fact that the start and end quote delimiter doesn't need to be exactly 3 `'` chars. It can be any odd number of `'`, so long as it is matched at the start and end.

**Comment by zaneduffield** [comment]
Sorry I just saw that was your last point in the list...

**Comment by Cirras** [comment]
I'm sure this is going to be a joy to implement in the grammar...
