### ISSUE TITLE
Handle NativeInt as a weak alias in Delphi 12

### ISSUE THREAD

**Issue by fourls** [integrated-application-development/sonar-delphi#81]
### Prerequisites

- [X] This improvement has not already been suggested.
- [X] This improvement would be generally useful, not specific to my code or setup.

### Engine area

Delphi language support

### Improvement description

In Delphi 11 and below, NativeInt is a "strong alias" that is equivalent to either Integer or Int64 (depending on the platform). In Delphi 12, the NativeInt data type is a "weak alias" that is **exactly equal to** Integer (on Win32) or Int64 (on Win64).

Because strong aliases have less weight when performing overload resolution, this change needs to be reflected in SonarDelphi. 
This should be accompanied with retooled support for type aliases, as there is currently no way to retrieve a type alias instead of the aliased type, and without full type alias support, SonarDelphi would not be able to detect NativeInt usages at all. This would have ramifications on several rules including PlatformDependentTruncation and PlatformDependentCast.

For more details, see [Marco Cantu's blog post describing the change](https://blogs.embarcadero.com/yukon-beta-blog-nativeint-as-a-weak-alias/) and [the RAD Studio documentation for System.NativeInt](https://docwiki.embarcadero.com/Libraries/Athens/en/System.NativeInt).

### Rationale

This is required to have accurate overload resolution on Delphi 12 code.

**Comment by Cirras** [comment]
The difficult part of this is now complete. 👍
Weak aliases are modeled in the type system as of b3b14dd58f27e1b5b5f5b65dfb53f37aced1b012.

**Comment by zaneduffield** [comment]
Note: the symmetric change was _not_ made to the `NativeUInt` type in Delphi 12

**Comment by zaneduffield** [comment]
Actually, I tested that theory using the wrong version of Delphi 🤦. `NativeUInt` was actually changed to a weak alias type as well (despite the documentation suggesting it was only `NativeInt` that changed).
