### ISSUE TITLE
[Bug]: Scan fails on a .dproj file that declares the same unit alias twice

### ISSUE THREAD

**Issue by fourls** [integrated-application-development/sonar-delphi#85]
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.0.0

### Issue description

In Delphi project files (.dproj) it is legal to have unit aliases defined more than once, e.g. in your dproj:

```xml
        <DCC_UnitAlias>Foo=Data.DB;Foo=System.SysUtils;$(DCC_UnitAlias)</DCC_UnitAlias>
```

This is perfectly legal, and the compiler uses the last set alias (so `Foo=System.SysUtils` in the above case). SonarDelphi currently fails with an analysis error upon encountering this:

![image](https://github.com/integrated-application-development/sonar-delphi/assets/28214458/323ec04c-38e0-4d40-a50e-db04d5a80bd8)

### Steps to reproduce

I've supplied a minimal case project below. Running a scan with SonarDelphi 1.0.0 reproduces the error. 

### Minimal Delphi code exhibiting the issue

[DuplicateUnitAliasTestProject.zip](https://github.com/integrated-application-development/sonar-delphi/files/13370612/DuplicateUnitAliasTestProject.zip)

**Comment by Cirras** [comment]
This one came as a surprise, I didn't know that `ImmutableSortedMap.Builder` had a problem with duplicate values.

**Comment by Cirras** [comment]
As discussed, I went ahead and did the "`TreeMap` wrapped with an unmodifiable map" approach in https://github.com/integrated-application-development/sonar-delphi/commit/8336adaa5abb5da296fba06a2fe2b9ff32faceb9.
