### ISSUE TITLE
[Bug]: Multiline compiler directives cause CPD executor to crash

### ISSUE THREAD

**Issue by fourls** [integrated-application-development/sonar-delphi#88]
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.0.0

### Issue description

Many compiler directives in Delphi allow newlines, meaning you can have the following:

```delphi
{$REGION

'xyz'

}
```

SonarDelphi currently fails to scan files with multiline compiler directives like the above, specifically on the CPD and highlight executors. This seems to be because the compiler directive token has been parsed as a single line, with `endLine` being the same as `startLine` and `endColumn` being what the end column would be if the entire compiler directive was on one line. This results in invalid file positions.

Note that this is a per-file crash and does not stop the entire analysis.

Stack traces:

![image](https://github.com/integrated-application-development/sonar-delphi/assets/28214458/eb098f93-f28e-4782-8e90-8847aec00991)
![image](https://github.com/integrated-application-development/sonar-delphi/assets/28214458/a7fed40e-32e3-4140-9354-e40f66e01849)

### Steps to reproduce

Scanning any file with multiline compiler directives should cause this issue.
I have attached a minimal case project below. 

### Minimal Delphi code exhibiting the issue

[MultilineDirectiveTestProject.zip](https://github.com/integrated-application-development/sonar-delphi/files/13371915/MultilineDirectiveTestProject.zip)

**Comment by fourls** [comment]
@Cirras Wondering what you think about this? It almost seems like an ANTLR bug from what I can see.

**Comment by Cirras** [comment]
> @Cirras Wondering what you think about this? It almost seems like an ANTLR bug from what I can see.

Nope! Close, though.
It was actually an oversight in the file position calculation, which we already handled correctly for comments.

See: `DelphiTokenImpl::calculatePosition`
