### ISSUE TITLE
Differences between the 'official' repo hosted by Embarcadero?

### ISSUE THREAD

**Issue by darianmiller** [integrated-application-development/sonar-delphi#90]
### Prerequisites

- [X] This question has not already been answered.
- [X] This question is about SonarDelphi, not SonarQube or Delphi.

### Inquiry

Are all the improvements from the official repo included in yours?

https://github.com/Embarcadero/SonarDelphi

**Comment by Cirras** [comment]
Hi @darianmiller,

Thanks for your question.

---

> Are all the improvements from the official repo included in yours?

The short answer is yes.

Our project predates the Embarcadero fork by a few years, and is a near-total rewrite of the original project.
So it's not a *total* apples-to-apples comparison.

With that being said - I've had a browse through all of the work done by [JAM Software](http://www.jam-software.com/) and [MendriX](http://www.mendrix.nl/), and am quite confident in saying we'd made all of the same improvements (most of them present as early as v0.0.1)

---

> Differences between the 'official' repo hosted by Embarcadero?

Too numerous to list, but here are some highlights as of v1.0.0:
* 120+ analysis rules (~70 more)
* Custom rules
    * via templates
    * via a programmatic Java API 
* Powerful semantic analysis
    * Analysis rules can leverage a full semantic model of your codebase
* Direct support for [DUnitX](https://github.com/VSoftTechnologies/DUnitX) test reports in the NUnit format
* Syntax highlighting
    * (listed in Embarcadero's README, but not implemented in that project)
* Support for:
   * Attributes
   * Inline const/var declarations
   * Binary literals
   * Digit separators in numeric literals 
   * (again, too numerous to list)

For a comprehensive list, see the [CHANGELOG](https://github.com/integrated-application-development/sonar-delphi/blob/master/CHANGELOG.md).
But most importantly, this project is actively maintained and open for contributions. 😄

**Comment by darianmiller** [comment]
Thanks for the detailed response!   Maybe @checkdigits
